openapi: 3.0.0
info:
  title: Message Service API
  version: 1.0.0
servers:
  - url: http://api-gateway:8080
paths:
  /messages/cache/{chatId}:
    delete:
      tags:
        - MessageController
      operationId: clearCache
      parameters:
        - name: chatId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
